name: veraicons
description: VeraUp Icons — 554 symboles en 10 styles (stroke, solid, duotone, twotone, bulk). Bibliothèque officielle VeraUp Inc.
version: 1.2.1
publish_to: none
repository: https://github.com/Veraup-Inc/veraicons
issue_tracker: https://github.com/Veraup-Inc/veraicons/issues
documentation: https://veraup-inc.github.io/veraicons/
topics: [icons, ui, svg, icon-font]
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
flutter:
  assets:
    - assets/duotone-rounded/
    - assets/duotone-standard/
    - assets/twotone-rounded/
    - assets/bulk-rounded/
  fonts:
    - family: VeraUpIconsStrokeRounded
      fonts:
        - asset: fonts/VeraUpIconsStrokeRounded.ttf
    - family: VeraUpIconsStrokeSharp
      fonts:
        - asset: fonts/VeraUpIconsStrokeSharp.ttf
    - family: VeraUpIconsStrokeStandard
      fonts:
        - asset: fonts/VeraUpIconsStrokeStandard.ttf
    - family: VeraUpIconsSolidRounded
      fonts:
        - asset: fonts/VeraUpIconsSolidRounded.ttf
    - family: VeraUpIconsSolidSharp
      fonts:
        - asset: fonts/VeraUpIconsSolidSharp.ttf
    - family: VeraUpIconsSolidStandard
      fonts:
        - asset: fonts/VeraUpIconsSolidStandard.ttf
